import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('startup story, navigation and an honest investor path are present', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Don’t buildalone.')
  await expect(page.locator('.hero__lead')).toHaveText('Meet people in Melbourne. Test a startup idea together. See if you’re a team.')
  await expect(page.getByRole('heading', { name: 'Pilot at a glance' })).toBeVisible()
  await expect(page.locator('.pilot-overview')).toContainText('Planned format')
  await expect(page.locator('.registration-next li')).toHaveCount(3)
  await expect(page.locator('.registration-next')).toContainText('Registering interest does not guarantee a place.')
  await expect(page.getByText('Spend 14 days on one small goal.', { exact: false })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'A real team. A tested idea. A clear next step.' })).toBeVisible()
  await expect(page.locator('.pilot-boundaries li')).toHaveText(['Keep your job or studies', 'No company required', 'No equity taken', 'No funding promised'])
  await expect(page.locator('body')).not.toContainText('validated idea')
  await expect(page.locator('body')).not.toContainText('path towards investors')
  await page.getByRole('link', { name: 'How it works', exact: true }).click()
  await expect(page).toHaveURL(/#how-it-works$/)
  await page.getByRole('link', { name: 'Register interest', exact: true }).click()
  await expect(page).toHaveURL(/#register$/)
  await expect(page.getByLabel('Your name')).toBeVisible()
  expect(errors).toEqual([])
})

test('form validates required fields, completes the preview and does not send data', async ({ page }) => {
  const outbound: string[] = []
  page.on('request', request => { if (request.method() === 'POST') outbound.push(request.url()) })
  await page.goto('/#register')
  await page.getByRole('button', { name: 'Preview registration' }).click()
  await expect(page.getByLabel('Your name')).toBeFocused()
  await expect(page.getByText('Please tell us your name.')).toBeVisible()
  await page.getByLabel('Your name').fill('Alex Example')
  await page.getByLabel('Email address').fill('invalid')
  await page.getByLabel('Your sector').selectOption('SaaS & software')
  await page.getByLabel('Your main skill').selectOption('Engineering & development')
  await page.getByRole('button', { name: 'Preview registration' }).click()
  await expect(page.getByLabel('Email address')).toBeFocused()
  await expect(page.getByText('Enter an email address, like you@example.com.')).toBeVisible()
  await page.getByLabel('Email address').fill('alex@example.com')
  await page.getByRole('button', { name: 'Preview registration' }).click()
  await expect(page.getByLabel('Someone who builds')).toBeFocused()
  await expect(page.getByText('Choose who you’d like to meet, or “Open to anyone”.')).toBeVisible()
  await expect(page.getByText('Choose how you like to work, or “Still finding out”.')).toBeVisible()
  await page.getByLabel('Someone who designs').check()
  await page.getByLabel('Open to anyone').check()
  await expect(page.getByLabel('Someone who designs')).not.toBeChecked()
  await page.getByLabel('Hands-on making').check()
  await page.getByRole('button', { name: 'Preview registration' }).click()
  await expect(page.getByLabel('Under 4 hours')).toBeFocused()
  await expect(page.getByText('Choose roughly how much time you could give.')).toBeVisible()
  await page.getByLabel('4–6 hours').check()
  await page.getByRole('button', { name: 'Preview registration' }).click()
  await expect(page.getByRole('heading', { name: 'That’s the first step.' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Know someone who should be in the room?' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Email' })).toHaveAttribute('href', /^mailto:\?subject=/)
  await expect(page.getByText('Your details have not been sent or saved', { exact: false })).toBeVisible()
  expect(outbound).toEqual([])
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
  await page.getByRole('button', { name: 'Try the form again' }).click()
  await expect(page.getByLabel('Your name')).toHaveValue('')
  await expect(page.getByLabel('Your name')).toBeFocused()
})

test('FAQ and privacy disclosure expand with keyboard and pointer', async ({ page }) => {
  await page.goto('/')
  await page.getByText('Will StartBeside connect us with investors?', { exact: true }).click()
  await expect(page.getByText('isn’t an investment fund or an investor-matching service', { exact: false })).toBeVisible()
  const summary = page.getByText('Do I need a startup idea already?', { exact: true })
  await summary.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByText('No. Bring a skill, a perspective', { exact: false })).toBeVisible()
  await page.getByRole('link', { name: 'Privacy details' }).click()
  await expect(page.locator('#privacy-content')).toHaveAttribute('open', '')
  await expect(page.getByText('This prototype does not submit, store or share', { exact: false })).toBeVisible()
})

test('film decodes audio/video, pauses, seeks, captions, replays and stops on close', async ({ page }) => {
  const mediaRequests: string[] = []
  page.on('request', request => { if (request.url().includes('startbeside-film.mp4')) mediaRequests.push(request.url()) })
  await page.goto('/')
  expect(mediaRequests).toEqual([])
  const watch = page.getByRole('button', { name: 'Watch the film' })
  await watch.click()
  const video = page.locator('dialog video')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Close the film' })).toBeFocused()
  await expect.poll(() => video.evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(.5)
  expect(await video.evaluate(v => (v as HTMLVideoElement).videoWidth)).toBe(1920)
  expect(await video.evaluate(v => (v as HTMLVideoElement).videoHeight)).toBe(1080)
  expect(await video.evaluate(v => (v as HTMLVideoElement & { webkitAudioDecodedByteCount: number }).webkitAudioDecodedByteCount)).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Pause the film' }).click()
  const position = await video.evaluate(v => (v as HTMLVideoElement).currentTime)
  await page.waitForTimeout(350)
  expect(await video.evaluate(v => (v as HTMLVideoElement).currentTime)).toBeCloseTo(position, 1)
  await page.getByRole('button', { name: 'Mute film', exact: true }).click()
  expect(await video.evaluate(v => (v as HTMLVideoElement).muted)).toBe(true)
  await page.getByRole('slider', { name: 'Film volume' }).fill('0.35')
  expect(await video.evaluate(v => (v as HTMLVideoElement).volume)).toBeCloseTo(.35)
  expect(await video.evaluate(v => (v as HTMLVideoElement).muted)).toBe(false)
  await page.getByRole('slider', { name: 'Film position' }).fill('6.5')
  await expect.poll(() => video.evaluate(v => ((v as HTMLVideoElement).textTracks[0]?.activeCues?.[0] as VTTCue)?.text)).toContain('At StartBeside')
  await page.getByRole('button', { name: 'English captions' }).click()
  expect(await video.evaluate(v => (v as HTMLVideoElement).textTracks[0].mode)).toBe('hidden')
  await page.getByRole('button', { name: 'English captions' }).click()
  expect(await video.evaluate(v => (v as HTMLVideoElement).textTracks[0].mode)).toBe('showing')
  await page.getByRole('slider', { name: 'Film position' }).fill('19.5')
  await page.getByRole('button', { name: 'Play the film', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Replay the film' })).toBeVisible()
  await page.getByRole('button', { name: 'Replay the film' }).click()
  await expect.poll(() => video.evaluate(v => (v as HTMLVideoElement).currentTime)).toBeLessThan(2)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect(await video.evaluate(v => (v as HTMLVideoElement).paused)).toBe(true)
  await expect(watch).toBeFocused()
  await watch.click()
  await expect.poll(() => video.evaluate(v => (v as HTMLVideoElement).currentTime)).toBeLessThan(2)
  await page.getByRole('button', { name: 'Find your people', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect(await video.evaluate(v => (v as HTMLVideoElement).paused)).toBe(true)
})

test('the film is discovered after the opening and only loads when requested', async ({ page }) => {
  // The full film (with sound) loads only on request; a short silent loop may load near its section.
  const mediaRequests: string[] = []
  const loopRequests: string[] = []
  page.on('request', request => {
    if (request.url().includes('startbeside-film.mp4')) mediaRequests.push(request.url())
    if (request.url().includes('startbeside-loop.mp4')) loopRequests.push(request.url())
  })
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    const watch = page.getByRole('button', { name: 'Watch the film' })
    expect((await watch.boundingBox())!.y).toBeGreaterThan(900)
    await expect(page.locator('.hero').getByRole('button', { name: 'Watch the film' })).toHaveCount(0)
    await page.getByRole('link', { name: 'See what comes together' }).click()
    await expect(page).toHaveURL(/#film$/)
    await watch.scrollIntoViewIfNeeded()
    await expect(page.locator('.film-feature__reveal')).toHaveCSS('opacity', '1')
    await expect(watch).toBeInViewport()
    expect(mediaRequests).toEqual([])
    await expect(page.locator('dialog video')).toHaveCount(0)
    const loop = page.locator('.film-feature__loop')
    await expect(loop).toHaveAttribute('aria-hidden', 'true')
    expect(await loop.evaluate(v => (v as HTMLVideoElement).muted)).toBe(true)
  }
  expect(loopRequests.length).toBeGreaterThan(0)
  const watch = page.getByRole('button', { name: 'Watch the film' })
  await watch.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect.poll(() => page.locator('dialog video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(.1)
  await page.keyboard.press('Escape')
  await expect(watch).toBeFocused()
  await expect(watch).toBeInViewport()
})

test('film window fits mobile, expands and provides a transcript', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Watch the film' }).click()
  await expect(page.getByRole('button', { name: 'Pause the film' })).toBeVisible()
  await page.getByRole('button', { name: 'Pause the film' }).click()
  const bounds = await page.getByRole('dialog').boundingBox()
  expect(bounds!.width).toBeLessThanOrEqual(390)
  expect(bounds!.height).toBeLessThanOrEqual(820)
  await page.getByText('Read the transcript', { exact: false }).click()
  await expect(page.getByText('Pilot note:', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Expand film window' }).click()
  await expect(page.getByRole('button', { name: 'Restore film window' })).toBeVisible()
  await page.getByRole('button', { name: 'Restore film window' }).click()
  await page.getByRole('button', { name: 'Close the film' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('mobile menu reaches the form and all target sizes avoid horizontal overflow', async ({ page }) => {
  test.setTimeout(45_000)
  for (const width of [320, 390, 760, 768, 1003, 1440, 1920]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await page.evaluate(() => document.fonts.ready)
    const artwork = page.locator('.hero .artwork')
    await artwork.scrollIntoViewIfNeeded()
    await expect(artwork).toHaveClass(/artwork--entrance/)
    // Wait for the timed entrance; scroll-linked motion has no end to wait for.
    await artwork.evaluate(node => Promise.all(node.getAnimations({ subtree: true }).filter(animation => animation.timeline === document.timeline).map(animation => animation.finished)))
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `overflow at ${width}px`).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await expect(page.getByRole('navigation', { name: 'Mobile navigation' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Mobile navigation' }).getByRole('link', { name: 'Register interest' }).click()
  await expect(page.getByRole('navigation', { name: 'Mobile navigation' })).not.toBeVisible()
  await expect(page).toHaveURL(/#register$/)
})

test('reduced motion keeps artwork visible and suppresses 3D movement', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.hero .artwork__whole')).toHaveCSS('opacity', '1')
  await page.locator('.hero .artwork').hover()
  await expect(page.locator('.hero .artwork__perspective')).toHaveCSS('transform', 'none')
  await expect(page.locator('.hero .artwork__piece').first()).toHaveCSS('display', 'none')
  await expect(page.locator('.film-feature__reveal')).toHaveCSS('opacity', '1')
  await expect(page.locator('.film-feature__reveal')).toHaveCSS('transform', 'none')
})

// Arrival motion fades text in; check contrast once it has settled, not mid-fade.
const settle = (page: import('@playwright/test').Page) => page.evaluate(() => Promise.all(document.getAnimations()
  .filter(animation => animation.timeline === document.timeline && Number.isFinite(Number(animation.effect?.getComputedTiming().endTime)))
  .map(animation => animation.finished.catch(() => {}))))

test('desktop, mobile, validation and story states pass automated accessibility checks', async ({ page }) => {
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/')
    await settle(page)
    expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  }
  await page.getByRole('button', { name: 'Preview registration' }).click()
  await settle(page)
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  await page.getByRole('button', { name: 'Watch the film' }).click()
  await page.getByRole('button', { name: 'Pause the film' }).click()
  await settle(page)
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
})

test('failed film loading keeps retry, transcript and dismissal available', async ({ page }) => {
  await page.route('**/media/startbeside-film.mp4', route => route.fulfill({ status: 404, body: 'Unavailable' }))
  await page.goto('/')
  await page.getByRole('button', { name: 'Watch the film' }).click()
  await expect(page.getByRole('alert')).toContainText('The film couldn’t load.')
  await expect(page.getByRole('button', { name: 'Try again' })).toBeVisible()
  await page.getByText('Read the transcript', { exact: false }).click()
  await expect(page.getByText('Pilot note:', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Close the film' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('browser autoplay refusal presents a working explicit play button', async ({ page }) => {
  await page.addInitScript(() => {
    const original = HTMLMediaElement.prototype.play
    const blocked = () => Promise.reject(new DOMException('User gesture required', 'NotAllowedError'))
    HTMLMediaElement.prototype.play = blocked
    document.addEventListener('click', event => {
      if ((event.target as Element).closest('.film-start')) HTMLMediaElement.prototype.play = original
    }, true)
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Watch the film' }).click()
  await expect(page.getByRole('button', { name: 'Play with sound' })).toBeVisible()
  expect(await page.locator('dialog video').evaluate(v => (v as HTMLVideoElement).paused)).toBe(true)
  await page.getByRole('button', { name: 'Play with sound' }).click()
  await expect.poll(() => page.locator('dialog video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBeGreaterThan(.5)
  await expect(page.getByRole('button', { name: 'Play with sound' })).not.toBeVisible()
})

test('choosing a piece completes the arch and prefills the form', async ({ page }) => {
  await page.goto('/')
  const finder = page.locator('#your-piece')
  await finder.scrollIntoViewIfNeeded()
  await expect(finder.getByRole('button', { name: 'Register with my piece' })).toBeDisabled()
  await finder.getByLabel(/I design/).check()
  await expect(finder.locator('.finder__result')).toContainText('You bring the design. Look for someone who builds or someone who grows it. A team of two can work too.')
  await expect(finder.locator('.finder-piece--right')).toHaveClass(/is-mine/)
  await expect(finder.locator('.finder-piece--left')).toHaveClass(/is-missing/)
  await finder.getByRole('button', { name: 'Register with my piece' }).click()
  await expect(finder.locator('.finder__stage')).toHaveClass(/is-complete/)
  await expect(page.getByRole('heading', { name: /The next chapter/ })).toBeFocused()
  await expect(page.getByLabel('Your main skill')).toHaveValue('Design & user experience')
  await expect(page.getByLabel('Someone who builds')).toBeChecked()
  await expect(page.getByLabel('Someone who grows it')).toBeChecked()
  await expect(page.getByLabel('Someone who designs')).not.toBeChecked()
  await expect(page.getByText('We’ve added your piece and who you’re looking for.', { exact: false })).toBeVisible()
})

test('the film ends on a card that leads to the piece finder', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.film-bridge img')).toHaveCount(2)
  await page.getByRole('button', { name: 'Watch the film' }).click()
  await page.getByRole('button', { name: 'Pause the film' }).click()
  await page.getByRole('slider', { name: 'Film position' }).fill('19.9')
  await page.getByRole('button', { name: 'Play the film', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Every gateway starts with one piece.' })).toBeVisible()
  await page.getByRole('button', { name: 'Find my missing piece', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.locator('#finder-title')).toBeFocused()
})

test('process steps animate in, hero stones carry labels and share tags are present', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.hero .artwork__label')).toHaveCount(3)
  await page.locator('.hero .artwork__hit--right').hover()
  await expect(page.locator('.hero .artwork__label--right')).toHaveCSS('opacity', '1')
  await page.locator('.process__steps').scrollIntoViewIfNeeded()
  await expect(page.locator('.process__steps')).toHaveClass(/is-live/)
  await expect(page.locator('.step-arch.is-done')).toHaveCount(1)
  const og = await page.locator('meta[property="og:image"]').getAttribute('content')
  expect(og).toMatch(/\/og\/startbeside-share\.jpg$/)
})
